SET NAMES UTF8;
SET SQL DIALECT 3;
CONNECT 'localhost/3050:D:/base.fdb' USER 'sysdba' PASSWORD 'masterkey';
SET AUTODDL ON;

/* COUNTRIES */
CREATE TABLE COUNTRIES (
    COUNTRY_NAME VARCHAR(3) NOT NULL,
    COUNTRY_CODE VARCHAR(50) NOT NULL,
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP);

/* FILMS */
CREATE TABLE FILMS (
    FILM_ID INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    RELESE_YEAR INTEGER,
    PRODUCT_TYPE VARCHAR(20),
    COUNTRY_CODE VARCHAR(3),
    DURATION INTEGER,
    DESCRIPTION BLOB SUB_TYPE TEXT SEGMENT SIZE 0,
    POSTER_PATH VARCHAR(500),
    RATING DECIMAL(3),
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATE TIMESTAMP);

/* ROLES */
CREATE TABLE ROLES (
    ROLE_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION BLOB SUB_TYPE TEXT SEGMENT SIZE 500,
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP);

/* COLLECTIONS */
CREATE TABLE COLLECTIONS (
    " COLLECTIONS_ID" INTEGER NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CREATED_COLLECTION TIMESTAMP);

/* ADMINS */
CREATE TABLE ADMINS (
    LOGIN VARCHAR(50) NOT NULL,
    PASWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL);

/* FILM_COLLECTION */
CREATE TABLE FILM_COLLECTION (
    FILM INTEGER NOT NULL,
    COLLECTION INTEGER NOT NULL);

/* FILM_CREW */
CREATE TABLE FILM_CREW (
    FILM_ID INTEGER NOT NULL,
    PEOPLE_ID INTEGER NOT NULL,
    TITLE_ROLE VARCHAR(50) NOT NULL,
    ROLE_FILM VARCHAR(100));

/* GENRES */
CREATE TABLE GENRES (
    GENRE_NAME VARCHAR(50) NOT NULL,
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP);

/* PEOPLE */
CREATE TABLE PEOPLE (
    PEOPLE_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PATRONYMIC VARCHAR(100),
    BIRTH_YEAR DATE,
    BIOGRAPHY BLOB SUB_TYPE TEXT SEGMENT SIZE 0,
    PHOTO VARCHAR(500),
    COUNTRY_CODE VARCHAR(3),
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP);

/* USERS */
CREATE TABLE USERS (
    USER_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    REGISTRATION_DATE TIMESTAMP);

/* FILM_GENRE */
CREATE TABLE FILM_GENRE (
    FILM_ID INTEGER NOT NULL,
    GENRE_NAME VARCHAR(50) NOT NULL);

/* COUNTRIES.PK_COUNTRIES */
ALTER TABLE COUNTRIES
ADD CONSTRAINT PK_COUNTRIES PRIMARY KEY (COUNTRY_CODE);

/* FILMS.PK_FILMS */
ALTER TABLE FILMS
ADD CONSTRAINT PK_FILMS PRIMARY KEY (FILM_ID);

/* ROLES.PK_ROLES_1 */
ALTER TABLE ROLES
ADD CONSTRAINT PK_ROLES_1 PRIMARY KEY (ROLE_NAME);

/* COLLECTIONS.PK_COLLECTIONS */
ALTER TABLE COLLECTIONS
ADD CONSTRAINT PK_COLLECTIONS PRIMARY KEY (COLLECTIONS_ID);

/* ADMINS.PK_ADMINS */
ALTER TABLE ADMINS
ADD CONSTRAINT PK_ADMINS PRIMARY KEY (LOGIN);

/* FILM_COLLECTION.PK_FILM_COLLECTION */
ALTER TABLE FILM_COLLECTION
ADD CONSTRAINT PK_FILM_COLLECTION PRIMARY KEY (FILM, COLLECTION);

/* FILM_CREW.PK_FILM_CREW */
ALTER TABLE FILM_CREW
ADD CONSTRAINT PK_FILM_CREW PRIMARY KEY (FILM_ID, PEOPLE_ID, TITLE_ROLE);

/* GENRES.GENRA_NAME */
ALTER TABLE GENRES
ADD CONSTRAINT GENRA_NAME PRIMARY KEY (GENRE_NAME);

/* PEOPLE.PK_PEOPLE */
ALTER TABLE PEOPLE
ADD CONSTRAINT PK_PEOPLE PRIMARY KEY (PEOPLE_ID);

/* USERS.PK_USERS_1 */
ALTER TABLE USERS
ADD CONSTRAINT PK_USERS_1 PRIMARY KEY (USER_NAME);

/* FILM_GENRE.PK_FILM_GENRE */
ALTER TABLE FILM_GENRE
ADD CONSTRAINT PK_FILM_GENRE PRIMARY KEY (FILM_ID, GENRE_NAME);

/* COUNTRIES.UQ_COUNTRIES_1 */
ALTER TABLE COUNTRIES
ADD CONSTRAINT UQ_COUNTRIES_1 UNIQUE (COUNTRY_NAME);

/* ADMINS.UQ_ADMINS_1 */
ALTER TABLE ADMINS
ADD CONSTRAINT UQ_ADMINS_1 UNIQUE (EMAIL);

/* USERS.UQ_USERS_1 */
ALTER TABLE USERS
ADD CONSTRAINT UQ_USERS_1 UNIQUE (EMAIL);

/* COUNTRIES.FK_COUNTRIES_1 */
ALTER TABLE COUNTRIES
ADD CONSTRAINT FK_COUNTRIES_1 FOREIGN KEY (CREATED_ADMIN) REFERENCES ADMINS (LOGIN);

/* FILMS.FK_FILMS_1 */
ALTER TABLE FILMS
ADD CONSTRAINT FK_FILMS_1 FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRIES (COUNTRY_CODE);

/* FILMS.FK_FILMS_2 */
ALTER TABLE FILMS
ADD CONSTRAINT FK_FILMS_2 FOREIGN KEY (CREATED_ADMIN) REFERENCES ADMINS (LOGIN);

/* ROLES.FK_ROLES_1 */
ALTER TABLE ROLES
ADD CONSTRAINT FK_ROLES_1 FOREIGN KEY (CREATED_ADMIN) REFERENCES ADMINS (LOGIN);

/* COLLECTIONS.FK_COLLECTIONS_1 */
ALTER TABLE COLLECTIONS
ADD CONSTRAINT FK_COLLECTIONS_1 FOREIGN KEY (USER_NAME) REFERENCES USERS (USER_NAME);

/* FILM_COLLECTION.FK_FILM_COLLECTION_2 */
ALTER TABLE FILM_COLLECTION
ADD CONSTRAINT FK_FILM_COLLECTION_2 FOREIGN KEY (COLLECTION) REFERENCES COLLECTIONS (COLLECTIONS_ID);

/* FILM_COLLECTION.FK_FILM_COLLECTION_3 */
ALTER TABLE FILM_COLLECTION
ADD CONSTRAINT FK_FILM_COLLECTION_3 FOREIGN KEY (FILM) REFERENCES FILMS (FILM_ID);

/* FILM_CREW.FK_FILM_CREW_1 */
ALTER TABLE FILM_CREW
ADD CONSTRAINT FK_FILM_CREW_1 FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID);

/* FILM_CREW.FK_FILM_CREW_2 */
ALTER TABLE FILM_CREW
ADD CONSTRAINT FK_FILM_CREW_2 FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE (PEOPLE_ID);

/* FILM_CREW.PK_FILM_CREW_1 */
ALTER TABLE FILM_CREW
ADD CONSTRAINT PK_FILM_CREW_1 FOREIGN KEY (TITLE_ROLE) REFERENCES ROLES (ROLE_NAME);

/* GENRES.CREATED_ADMIN */
ALTER TABLE GENRES
ADD CONSTRAINT CREATED_ADMIN FOREIGN KEY (CREATED_ADMIN) REFERENCES ADMINS (LOGIN);

/* PEOPLE.FK_PEOPLE_1 */
ALTER TABLE PEOPLE
ADD CONSTRAINT FK_PEOPLE_1 FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRIES (COUNTRY_CODE);

/* PEOPLE.FK_PEOPLE_2 */
ALTER TABLE PEOPLE
ADD CONSTRAINT FK_PEOPLE_2 FOREIGN KEY (CREATED_ADMIN) REFERENCES ADMINS (LOGIN);

/* FILM_GENRE.FK_FILM_GENRE_1 */
ALTER TABLE FILM_GENRE
ADD CONSTRAINT FK_FILM_GENRE_1 FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID);

/* FILM_GENRE.FK_FILM_GENRE_2 */
ALTER TABLE FILM_GENRE
ADD CONSTRAINT FK_FILM_GENRE_2 FOREIGN KEY (GENRE_NAME) REFERENCES GENRES (GENRE_NAME);

/* FILMS.CHECK_FILMS_1 */
ALTER TABLE FILMS
ADD CONSTRAINT CHECK_FILMS_1 CHECK(RATING >= 0 AND RATING <= 10
);

/* FILMS.CHECK_FILMS_2 */
ALTER TABLE FILMS
ADD CONSTRAINT CHECK_FILMS_2 CHECK(
	DURATION > 0
);


