SET NAMES UTF8;
SET SQL DIALECT 3;
CONNECT 'localhost/3050:D:/base.fdb' USER 'sysdba' PASSWORD 'masterkey';
SET AUTODDL ON;

/* COUNTRIES */
CREATE TABLE COUNTRIES (
    COUNTRY_NAME VARCHAR(3) NOT NULL,
    COUNTRY_CODE VARCHAR(50) NOT NULL,
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* FILMS */
CREATE TABLE FILMS (
    FILM_ID INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    RELESE_YEAR INTEGER,
    PRODUCT_TYPE VARCHAR(20),
    COUNTRY_CODE VARCHAR(3),
    DURATION INTEGER,
    POSTER_PATH VARCHAR(500),
    RATING DECIMAL(3),
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION VARCHAR(500));

/* ROLES */
CREATE TABLE ROLES (
    ROLE_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION BLOB SUB_TYPE TEXT SEGMENT SIZE 500,
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* COLLECTIONS */
CREATE TABLE COLLECTIONS (
    COLLECTIONS_ID INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CREATED_COLLECTION TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* ADMINS */
CREATE TABLE ADMINS (
    LOGIN VARCHAR(50) NOT NULL,
    PASWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_CREATED TIMESTAMP,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* FILM_COLLECTION */
CREATE TABLE FILM_COLLECTION (
    FILM INTEGER NOT NULL,
    COLLECTION INTEGER NOT NULL);

/* FILM_CREW */
CREATE TABLE FILM_CREW (
    FILM_ID INTEGER NOT NULL,
    PEOPLE_ID INTEGER NOT NULL,
    TITLE_ROLE VARCHAR(50) NOT NULL,
    ROLE_FILM VARCHAR(100));

/* GENRES */
CREATE TABLE GENRES (
    GENRE_NAME VARCHAR(50) NOT NULL,
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* PEOPLE */
CREATE TABLE PEOPLE (
    PEOPLE_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PATRONYMIC VARCHAR(100),
    BIRTH_YEAR DATE,
    BIOGRAPHY BLOB SUB_TYPE TEXT SEGMENT SIZE 0,
    PHOTO VARCHAR(500),
    COUNTRY_CODE VARCHAR(3),
    CREATED_ADMIN VARCHAR(50),
    CREATED_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* USERS */
CREATE TABLE USERS (
    USER_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

/* FILM_GENRE */
CREATE TABLE FILM_GENRE (
    FILM_ID INTEGER NOT NULL,
    GENRE_NAME VARCHAR(50) NOT NULL);

/* ADD_FILM_CREW */
CREATE OR ALTER PROCEDURE ADD_FILM_CREW (
	FILM_ID INTEGER,
	PEOPLE_ID INTEGER,
	TITLE_ROLE VARCHAR(50),
	ROLE_FILM VARCHAR(100)
) 
AS BEGIN END;

/* ADD_FILM_GENRE */
CREATE OR ALTER PROCEDURE ADD_FILM_GENRE (
	FILM_ID INTEGER,
	GENRE_NAME VARCHAR(50)
) 
AS BEGIN END;

/* ADD_PERSON */
CREATE OR ALTER PROCEDURE ADD_PERSON (
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	PATRONYMIC VARCHAR(100),
	BIRTH_YEAR DATE,
	BIOGRAPHY BLOB SUB_TYPE TEXT,
	PHOTO VARCHAR(500),
	COUNTRY_CODE VARCHAR(3),
	CREATED_ADMIN VARCHAR(50)
) 
RETURNS (
	NEW_PERSON_ID INTEGER
)
AS BEGIN 
	SUSPEND;
END;

/* DELETE_FILM */
CREATE OR ALTER PROCEDURE DELETE_FILM (
	FILM_ID INTEGER
) 
AS BEGIN END;

/* ADD_FILM */
CREATE OR ALTER PROCEDURE ADD_FILM (
	TITLE VARCHAR(255),
	RELESE_YEAR INTEGER,
	PRODUCT_TYPE VARCHAR(20),
	COUNTRY_CODE VARCHAR(3),
	DURATION INTEGER,
	DESCRIPTION BLOB SUB_TYPE TEXT,
	POSTER_PATH VARCHAR(500),
	RATING DECIMAL(3,1),
	CREATED_ADMIN VARCHAR(50)
) 
RETURNS (
	NEW_FILM_ID INTEGER
)
AS BEGIN 
	SUSPEND;
END;

/* ADD_FILM_TO_COLLECTION */
CREATE OR ALTER PROCEDURE ADD_FILM_TO_COLLECTION (
	FILM_ID INTEGER,
	COLLECTION_ID INTEGER
) 
AS BEGIN END;

/* CREATE_COLLECTION */
CREATE OR ALTER PROCEDURE CREATE_COLLECTION (
	USER_NAME VARCHAR(50),
	TITLE VARCHAR(255),
	DESCRIPTION VARCHAR(1000)
) 
RETURNS (
	NEW_COLLECTION_ID INTEGER
)
AS BEGIN 
	SUSPEND;
END;

/* REGISTER_USER */
CREATE OR ALTER PROCEDURE REGISTER_USER (
	USER_NAME VARCHAR(50),
	EMAIL VARCHAR(100)
) 
AS BEGIN END;

/* GET_FILM_DETAILS */
CREATE OR ALTER PROCEDURE GET_FILM_DETAILS (
	FILM_ID INTEGER
) 
RETURNS (
	TITLE VARCHAR(255),
	RELESE_YEAR INTEGER,
	PRODUCT_TYPE VARCHAR(20),
	COUNTRY_NAME VARCHAR(50),
	DURATION INTEGER,
	DESCRIPTION BLOB SUB_TYPE TEXT,
	POSTER_PATH VARCHAR(500),
	RATING DECIMAL(3,1),
	CREATED_DATE TIMESTAMP
)
AS BEGIN 
	SUSPEND;
END;

/* BI_COLLECTIONS_ID */
CREATE OR ALTER TRIGGER BI_COLLECTIONS_ID
	FOR COLLECTIONS BEFORE INSERT
AS BEGIN END;

/* BI_FILMS_ID */
CREATE OR ALTER TRIGGER BI_FILMS_ID
	FOR FILMS BEFORE INSERT
AS BEGIN END;

/* BI_PEOPLE_ID */
CREATE OR ALTER TRIGGER BI_PEOPLE_ID
	FOR PEOPLE BEFORE INSERT
AS BEGIN END;

/* ADD_FILM_CREW */
CREATE OR ALTER PROCEDURE ADD_FILM_CREW (
	FILM_ID INTEGER,
	PEOPLE_ID INTEGER,
	TITLE_ROLE VARCHAR(50),
	ROLE_FILM VARCHAR(100)
) 
AS
BEGIN
    INSERT INTO FILM_CREW (FILM_ID, PEOPLE_ID, TITLE_ROLE, ROLE_FILM)
    VALUES (:FILM_ID, :PEOPLE_ID, :TITLE_ROLE, :ROLE_FILM);
END;

/* ADD_FILM_GENRE */
CREATE OR ALTER PROCEDURE ADD_FILM_GENRE (
	FILM_ID INTEGER,
	GENRE_NAME VARCHAR(50)
) 
AS
BEGIN
    INSERT INTO FILM_GENRE (FILM_ID, GENRE_NAME)
    VALUES (:FILM_ID, :GENRE_NAME);
END;

/* ADD_PERSON */
CREATE OR ALTER PROCEDURE ADD_PERSON (
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	PATRONYMIC VARCHAR(100),
	BIRTH_YEAR DATE,
	BIOGRAPHY BLOB SUB_TYPE TEXT,
	PHOTO VARCHAR(500),
	COUNTRY_CODE VARCHAR(3),
	CREATED_ADMIN VARCHAR(50)
) 
RETURNS (
	NEW_PERSON_ID INTEGER
)
AS
BEGIN
    INSERT INTO PEOPLE (
        FIRST_NAME, LAST_NAME, PATRONYMIC, BIRTH_YEAR,
        BIOGRAPHY, PHOTO, COUNTRY_CODE, CREATED_ADMIN
    ) VALUES (
        :FIRST_NAME, :LAST_NAME, :PATRONYMIC, :BIRTH_YEAR,
        :BIOGRAPHY, :PHOTO, :COUNTRY_CODE, :CREATED_ADMIN
    ) RETURNING PEOPLE_ID INTO NEW_PERSON_ID;
END;

/* DELETE_FILM */
CREATE OR ALTER PROCEDURE DELETE_FILM (
	FILM_ID INTEGER
) 
AS
BEGIN
    DELETE FROM FILM_GENRE WHERE FILM_ID = :FILM_ID;
    DELETE FROM FILM_CREW WHERE FILM_ID = :FILM_ID;
    DELETE FROM FILM_COLLECTION WHERE FILM = :FILM_ID;
    DELETE FROM FILMS WHERE FILM_ID = :FILM_ID;
END;

/* ADD_FILM */
CREATE OR ALTER PROCEDURE ADD_FILM (
	TITLE VARCHAR(255),
	RELESE_YEAR INTEGER,
	PRODUCT_TYPE VARCHAR(20),
	COUNTRY_CODE VARCHAR(3),
	DURATION INTEGER,
	DESCRIPTION BLOB SUB_TYPE TEXT,
	POSTER_PATH VARCHAR(500),
	RATING DECIMAL(3,1),
	CREATED_ADMIN VARCHAR(50)
) 
RETURNS (
	NEW_FILM_ID INTEGER
)
AS
BEGIN
    INSERT INTO FILMS (
        TITLE, RELESE_YEAR, PRODUCT_TYPE, COUNTRY_CODE, 
        DURATION, DESCRIPTION, POSTER_PATH, RATING, CREATED_ADMIN
    ) VALUES (
        :TITLE, :RELESE_YEAR, :PRODUCT_TYPE, :COUNTRY_CODE,
        :DURATION, :DESCRIPTION, :POSTER_PATH, :RATING, :CREATED_ADMIN
    ) RETURNING FILM_ID INTO NEW_FILM_ID;
END;

/* ADD_FILM_TO_COLLECTION */
CREATE OR ALTER PROCEDURE ADD_FILM_TO_COLLECTION (
	FILM_ID INTEGER,
	COLLECTION_ID INTEGER
) 
AS
BEGIN
    INSERT INTO FILM_COLLECTION (FILM, COLLECTION)
    VALUES (:FILM_ID, :COLLECTION_ID);
END;

/* CREATE_COLLECTION */
CREATE OR ALTER PROCEDURE CREATE_COLLECTION (
	USER_NAME VARCHAR(50),
	TITLE VARCHAR(255),
	DESCRIPTION VARCHAR(1000)
) 
RETURNS (
	NEW_COLLECTION_ID INTEGER
)
AS
BEGIN
    INSERT INTO COLLECTIONS (USER_NAME, TITLE, DESCRIPTION)
    VALUES (:USER_NAME, :TITLE, :DESCRIPTION)
    RETURNING COLLECTIONS_ID INTO NEW_COLLECTION_ID;
END;

/* REGISTER_USER */
CREATE OR ALTER PROCEDURE REGISTER_USER (
	USER_NAME VARCHAR(50),
	EMAIL VARCHAR(100)
) 
AS
BEGIN
    INSERT INTO USERS (USER_NAME, EMAIL)
    VALUES (:USER_NAME, :EMAIL);
END;

/* GET_FILM_DETAILS */
CREATE OR ALTER PROCEDURE GET_FILM_DETAILS (
	FILM_ID INTEGER
) 
RETURNS (
	TITLE VARCHAR(255),
	RELESE_YEAR INTEGER,
	PRODUCT_TYPE VARCHAR(20),
	COUNTRY_NAME VARCHAR(50),
	DURATION INTEGER,
	DESCRIPTION BLOB SUB_TYPE TEXT,
	POSTER_PATH VARCHAR(500),
	RATING DECIMAL(3,1),
	CREATED_DATE TIMESTAMP
)
AS
BEGIN
    SELECT 
        f.TITLE, f.RELESE_YEAR, f.PRODUCT_TYPE, c.COUNTRY_NAME,
        f.DURATION, f.DESCRIPTION, f.POSTER_PATH, f.RATING, f.CREATED_DATE
    FROM FILMS f
    JOIN COUNTRIES c ON f.COUNTRY_CODE = c.COUNTRY_CODE
    WHERE f.FILM_ID = :FILM_ID
    INTO :TITLE, :RELESE_YEAR, :PRODUCT_TYPE, :COUNTRY_NAME, 
         :DURATION, :DESCRIPTION, :POSTER_PATH, :RATING, :CREATED_DATE;
    
    SUSPEND;
END;

/* BI_COLLECTIONS_ID */
CREATE OR ALTER TRIGGER BI_COLLECTIONS_ID FOR COLLECTIONS
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE NEXT_ID INTEGER;
BEGIN
    IF (NEW.COLLECTIONS_ID IS NULL) THEN
    BEGIN
        SELECT COALESCE(MAX(COLLECTIONS_ID), 0) + 1 FROM COLLECTIONS INTO NEXT_ID;
        NEW.COLLECTIONS_ID = NEXT_ID;
    END
END;

/* BI_FILMS_ID */
CREATE OR ALTER TRIGGER BI_FILMS_ID FOR FILMS
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE NEXT_ID INTEGER;
BEGIN
    IF (NEW.FILM_ID IS NULL) THEN
    BEGIN
        -- Если таблица пустая - начинаем с 1, иначе MAX + 1
        SELECT COALESCE(MAX(FILM_ID), 0) + 1 FROM FILMS INTO NEXT_ID;
        NEW.FILM_ID = NEXT_ID;
    END
END;

/* BI_PEOPLE_ID */
CREATE OR ALTER TRIGGER BI_PEOPLE_ID FOR PEOPLE
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE NEXT_ID INTEGER;
BEGIN
    IF (NEW.PEOPLE_ID IS NULL) THEN
    BEGIN
        SELECT COALESCE(MAX(PEOPLE_ID), 0) + 1 FROM PEOPLE INTO NEXT_ID;
        NEW.PEOPLE_ID = NEXT_ID;
    END
END;


